// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://humdymxilcchyavkzifs.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imh1bWR5bXhpbGNjaHlhdmt6aWZzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ0NzI3MTQsImV4cCI6MjA2MDA0ODcxNH0.Zlo3tUlfdcIM4fWKSfcHoPlfpjzQEP3rPiPqcFydBJM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);